### ISSUE TITLE
Game crash on trying to render computers on physics object with CC:VS

### ISSUE THREAD

**Issue by UltrioG** [TechTastic/CC-VS#10]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

## Preface (Not important)
Due to Clockwork's recent removal of hot air balloons, I would instead have to either use Eureka! for its flying ships, or create a drone. I chose the latter option, as it was much cooler. However, quadcopters are famously unstable, and thus I would be required to use a PID control system to control my drone. Thus began the insanity.

## The Problem
When a physics object with a computer was assembled, the server crashes (java.lang.NoSuchMethodError).

## Expected
...that this wouldn't happen.

### Issue reproduction

1. Install Kotlin for Forge, Create, CC: Tweaked, Valkyrien Skies, Clockwork and CC: VS.
2. Place down a computer in a world, preferably in a testing world.
3. Select the computer with a wanderwand.
4. Assemble either via the Physics Infuser or Creative Gravitron.
5. Game crashes.

### Logs

[latest.log](https://github.com/user-attachments/files/16487170/latest.log)
[debug.log](https://github.com/user-attachments/files/16487171/debug.log)

**Comment by TechTastic** [comment]
Downgrade CC: Tweaked, it broke my Mixins with its latest update
