### ISSUE TITLE
Doesn't work with latest CC version

### ISSUE THREAD

**Issue by Mega2223** [TechTastic/CC-VS#11]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Fabric

### Issue description

When starting a computer withing a ship the game instantly crashes.
I tried downgrading my CC version and it worked fine.
Bug only occurs on version 1.112.0 of CC:T

### Issue reproduction

Download VS, CC etc. (1.20.1)
Build a ship.
Start a computer which is into said ship.
Instant crash.

### Logs

[latest.log](https://github.com/user-attachments/files/16489965/latest.log)
Could not find a debug.log file

**Comment by Otzelix** [comment]
can confirm, happens to me too

**Comment by JackTheRedCreeper** [comment]
Agreed, seems like the "add API" method has been changed

**Comment by TechTastic** [comment]
Downgrade CC: Tweaked, it broke my Mixins with its latest update
