### ISSUE TITLE
ship.getVelocity() doesn't give right velocity readings when moving slow

### ISSUE THREAD

**Issue by 19PHOBOSS98** [TechTastic/CC-VS#13]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

I tried comparing the APIs getVelocity method with my own velocity calculation. 
```
local ship_global_position = ship.getWorldspacePosition()
ship_global_position = vector.new(ship_global_position .x,ship_global_position .y,ship_global_position .z)
local my_vel = (ship_global_position - prev_pos)/0.05

print(textutils.serialise({ship_global_velocity=ship.getVelocity(),my_vel=my_vel}))
```
The ship was slowly rising up at the time. I expected them both to have a reading of at least positive Y. It turns out that ship.getVelocity() returns a negative number even though the ship was moving up albeit slowly.
![image](https://github.com/user-attachments/assets/30a1add0-9d33-4148-a58a-0406dff92056)

### Issue reproduction

Use a command computer to get a ship to slowly rise straight up (around 0.02 m/s).

**Comment by TechTastic** [comment]
Weird but not something for me to fix as the velocity values are gotten directly from the Ship itself
