### ISSUE TITLE
Crash upon placing an advanced computer or computer on a clockwork created VS Ship

### ISSUE THREAD

**Issue by Cavin-V** [TechTastic/CC-VS#14]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

When placing any computer onto a Valkyrian Skies ship created through the Create Clockwork mod, the game/server immidiately crashes with the attatched crash log.

I originally attempted this with several additional mods on a server, but was surprised to see it still occur in both singleplayer, and with only the required mods being used.

### Issue reproduction

Create a Valkyrian Skies ship through Clockwork.
Place a Computercraft computer onto the ship once formed.
Use the computer to open its interface.

### Logs

[crash-2024-09-26_23.16.38-server.txt](https://github.com/user-attachments/files/17158545/crash-2024-09-26_23.16.38-server.txt)
[latest.log](https://github.com/user-attachments/files/17158542/latest.log)

**Comment by TechTastic** [comment]
Fixed in latest Github 1.20 branch
