### ISSUE TITLE
[Feature Request] Add a function to "auto-reset" a computer on a newly assembled ship

### ISSUE THREAD

**Issue by 19PHOBOSS98** [TechTastic/CC-VS#16]
This is related to my bug report: https://github.com/TechTastic/CC-VS/issues/12#issue-2510653432

In short, I have to break and place my turtle back on the ship to get it to recognize the ship API. What if CC:VS adds a new global function that users can manually use to trigger a computer into checking if it's currently on a ship and refreshing itself?
something like:

`tryRefreshVS2API()`

**Comment by TechTastic** [comment]
Unfortunately, to do so requires access to both a `Level` and `BlockPos` which we cannot get via normal means
