### ISSUE TITLE
Inaccurate angle from ship.getYaw 

### ISSUE THREAD

**Issue by iknowwhatmdoingtotally** [TechTastic/CC-VS#17]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

the rotation given by the ship.getYaw method functions differently than in previous versions. 
Rotation does not go form -180 to 0 to 180, instead rotation goes from 0 to -90 to 0 to 90 to 0. This results in the method returning  the same number to describe two different rotations.

### Issue reproduction

To reproduce this issue make a ship rotate to an angle mirrored across the z axis, both of of these rotations will cause ship.getYaw to return the exact same value.

this returns an angle in radians of 0.78539816339745
![451](https://github.com/user-attachments/assets/21cf6410-74f1-444f-8b23-3f49f4554c2c)

this also returns an angle in radians of 0.78539816339745
![452](https://github.com/user-attachments/assets/cc9258e8-e73e-42f8-8d3f-c386ca874265)

**Comment by TechTastic** [comment]
It was Gimbal Lock, now fixed
