### ISSUE TITLE
[Forge, ver. 0.0.8] Setting the ship's scale to 0 causes significant block update lag, unloads(?) ship

### ISSUE THREAD

**Issue by PortalInTime** [TechTastic/CC-VS#2]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.19

### Mod Loader

Forge

### Issue description

Setting the ship's scale to `1/0` has caused significant lag in block updates, such as when changing the textures of Create's Copycats, and Minecraft is using all the RAM I've allocated to it. This issue had caused the ship to change scale for a single frame before disappearing completely, to the point where using Valkyrian Skies' built-in /vs command wouldn't list the ship, although I'm not sure if using autocomplete with /vs would list any unloaded ships in the first place.

The world still saves and loads, strangely enough.

### Issue reproduction

I was messing with the extended ship API, setting the ship's scale to `1/analogueRedstoneInput` (using Create's analogue lever, in this case), forgetting to prevent it from changing the scale when the redstone signal input is set to `0`. I think the world might be a lost cause now, which isn't much of an issue since I made it just to test with VS, but should still be resolved in case anybody else tries to divide their ship by zero.

**Comment by TechTastic** [comment]
This is an issue with VS2 itself imo as it uses their own code for setting Ship scales
