### ISSUE TITLE
Ship.getMass returns the ship's weight as the default weight of the ship's blocks, even if the block weights have been changed via datapack

### ISSUE THREAD

**Issue by thetheaplant** [TechTastic/CC-VS#3]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.18

### Mod Loader

Forge

### Issue description

If you change the weights of blocks with a datapack, getMass will still read those blocks as their original weight, even if the ship is physically lighter.

### Issue reproduction

Change the default blockweights with a datapack, like the one attached, then run ship.getMass() on a ship made out of the blocks which have had their weight changed.
[vs2_100kgV1_0.zip](https://github.com/TechTastic/CC-VS/files/14501864/vs2_100kgV1_0.zip)

**Comment by TechTastic** [comment]
Imo, this seems like a VS2 issue as getMass() simply calls LoadedServerShip.getMass()
