### ISSUE TITLE
[Feature Request] Better wireless modem range increases linearly

### ISSUE THREAD

**Issue by xiewuzhiying** [TechTastic/CC-VS#4]
When the wireless modem is on a ship, its range increases linearly based on the height in world space rather than the height in shipyard. (and can be more than 384 blocks)

Influenced by [#955](https://github.com/cc-tweaked/CC-Tweaked/issues/955) and [#1688](https://github.com/cc-tweaked/CC-Tweaked/issues/1688)

**Comment by TechTastic** [comment]
This is correct behavior for how the compatability Mixin was written into VS2

I do not understand what you would like me to do as this seems to already function as is and is not a thing for CC: VS to change as the Mixin is in base VS2 itself

**Comment by xiewuzhiying** [comment]
[WirelessModemPeripheral.java](https://github.com/cc-tweaked/CC-Tweaked/blob/mc-1.18.x/src/main/java/dan200/computercraft/shared/peripheral/modem/wireless/WirelessModemPeripheral.java)
The range is only related to the height of the wireless modem in shipyard.
Maybe I should record a video.

**Comment by xiewuzhiying** [comment]
And I hope the range can continue to increase at height beyond the max build height, such as an aerial VS ship being used as a wireless communication hub.

It should be something added by addon, not VS2.

**Comment by xiewuzhiying** [comment]
I did it myself.
