### ISSUE TITLE
`ship.getPitch()` always returns `nan`

### ISSUE THREAD

**Issue by Saftur** [TechTastic/CC-VS#6]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20​

### Mod Loader

Forge

### Issue description

Whenever I try to use `ship.getPitch()`, it just returns `nan` rather than any useful value. `ship.getRoll()` and `ship.getYaw()` work just fine, it's specifically `ship.getPitch()` that doesn't work.

### Issue reproduction

1. Create a platform
2. Infuse with physics
3. Place CC computer on physics-infused platform
4. Start computer, enter `lua`, followed by `ship.getPitch()`

**Comment by TechTastic** [comment]
Update your CC:VS
